/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ArticleBeanForm.java
 *
 * Created on 6 janv. 2011, 15:00:49
 */

package com.bash.jcouture.gui;

import javax.swing.JPanel;

/**
 *
 * @author bashizip
 */
public class ArticleBeanForm extends JPanel {

    /** Creates new form ArticleBeanForm */
    public ArticleBeanForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
