import java.awt.*;
import java.awt.event.*;
import java.io.*;
import javax.swing.*;
import java.text.*;
/*
 * Enregistrer_Facture_Cee.java
 *
 * Created on 17 novembre 2005, 17:03
 */

/**
 *
 * @author  Sébastien
 */
public class Nouvelle_Facture_Cee extends javax.swing.JInternalFrame {
    Facture cee;
    double ttc;
    double tva;
    double ht;
    //String nom;
    /** Creates new form Enregistrer_Facture_Cee */
    public Nouvelle_Facture_Cee() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        txtPrixTTC19 = new javax.swing.JTextField();
        txtPrixTTC18 = new javax.swing.JTextField();
        txtPrixTTC17 = new javax.swing.JTextField();
        txtPrixTTC16 = new javax.swing.JTextField();
        txtPrixTTC15 = new javax.swing.JTextField();
        txtPrixTTC14 = new javax.swing.JTextField();
        txtPrixTTC13 = new javax.swing.JTextField();
        txtPrixTTC12 = new javax.swing.JTextField();
        txtPrixTTC11 = new javax.swing.JTextField();
        txtPrixTTC10 = new javax.swing.JTextField();
        txtPrixTTC9 = new javax.swing.JTextField();
        txtPrixTTC8 = new javax.swing.JTextField();
        txtPrixTTC7 = new javax.swing.JTextField();
        txtPrixTTC6 = new javax.swing.JTextField();
        txtPrixTTC5 = new javax.swing.JTextField();
        txtPrixTTC4 = new javax.swing.JTextField();
        txtPrixTTC3 = new javax.swing.JTextField();
        txtPrixTTC2 = new javax.swing.JTextField();
        txtPrixTTC1 = new javax.swing.JTextField();
        txtPrixTTC0 = new javax.swing.JTextField();
        txtPrixHT = new javax.swing.JTextField();
        txtTVA = new javax.swing.JTextField();
        lblTVA = new javax.swing.JLabel();
        lblPrixHT = new javax.swing.JLabel();
        txtPrixTTC = new javax.swing.JTextField();
        lblTTC = new javax.swing.JLabel();
        txtPrixUnitaire0 = new javax.swing.JTextField();
        txtPrixUnitaire1 = new javax.swing.JTextField();
        txtPrixUnitaire2 = new javax.swing.JTextField();
        txtPrixUnitaire3 = new javax.swing.JTextField();
        txtPrixUnitaire4 = new javax.swing.JTextField();
        txtPrixUnitaire5 = new javax.swing.JTextField();
        txtPrixUnitaire6 = new javax.swing.JTextField();
        txtPrixUnitaire7 = new javax.swing.JTextField();
        txtPrixUnitaire8 = new javax.swing.JTextField();
        txtPrixUnitaire9 = new javax.swing.JTextField();
        txtPrixUnitaire10 = new javax.swing.JTextField();
        txtPrixUnitaire11 = new javax.swing.JTextField();
        txtPrixUnitaire12 = new javax.swing.JTextField();
        txtPrixUnitaire13 = new javax.swing.JTextField();
        txtPrixUnitaire14 = new javax.swing.JTextField();
        txtPrixUnitaire15 = new javax.swing.JTextField();
        txtPrixUnitaire16 = new javax.swing.JTextField();
        txtPrixUnitaire17 = new javax.swing.JTextField();
        txtPrixUnitaire18 = new javax.swing.JTextField();
        txtPrixUnitaire19 = new javax.swing.JTextField();
        txtQte0 = new javax.swing.JTextField();
        txtQte1 = new javax.swing.JTextField();
        txtQte2 = new javax.swing.JTextField();
        txtQte3 = new javax.swing.JTextField();
        txtQte4 = new javax.swing.JTextField();
        txtQte5 = new javax.swing.JTextField();
        txtQte6 = new javax.swing.JTextField();
        txtQte7 = new javax.swing.JTextField();
        txtQte8 = new javax.swing.JTextField();
        txtQte9 = new javax.swing.JTextField();
        txtQte10 = new javax.swing.JTextField();
        txtQte11 = new javax.swing.JTextField();
        txtQte12 = new javax.swing.JTextField();
        txtQte13 = new javax.swing.JTextField();
        txtQte14 = new javax.swing.JTextField();
        txtQte15 = new javax.swing.JTextField();
        txtQte16 = new javax.swing.JTextField();
        txtQte17 = new javax.swing.JTextField();
        txtQte18 = new javax.swing.JTextField();
        txtQte19 = new javax.swing.JTextField();
        txtDesignation0 = new javax.swing.JTextField();
        txtDesignation1 = new javax.swing.JTextField();
        txtDesignation2 = new javax.swing.JTextField();
        txtDesignation3 = new javax.swing.JTextField();
        txtDesignation4 = new javax.swing.JTextField();
        txtDesignation5 = new javax.swing.JTextField();
        txtDesignation6 = new javax.swing.JTextField();
        txtDesignation7 = new javax.swing.JTextField();
        txtDesignation8 = new javax.swing.JTextField();
        txtDesignation9 = new javax.swing.JTextField();
        txtDesignation10 = new javax.swing.JTextField();
        txtDesignation11 = new javax.swing.JTextField();
        txtDesignation12 = new javax.swing.JTextField();
        txtDesignation13 = new javax.swing.JTextField();
        txtDesignation14 = new javax.swing.JTextField();
        txtDesignation15 = new javax.swing.JTextField();
        txtDesignation16 = new javax.swing.JTextField();
        txtDesignation17 = new javax.swing.JTextField();
        txtDesignation18 = new javax.swing.JTextField();
        txtDesignation19 = new javax.swing.JTextField();
        txtNumero0 = new javax.swing.JTextField();
        txtNumero1 = new javax.swing.JTextField();
        txtNumero2 = new javax.swing.JTextField();
        txtNumero3 = new javax.swing.JTextField();
        txtNumero4 = new javax.swing.JTextField();
        txtNumero5 = new javax.swing.JTextField();
        txtNumero6 = new javax.swing.JTextField();
        txtNumero7 = new javax.swing.JTextField();
        txtNumero8 = new javax.swing.JTextField();
        txtNumero9 = new javax.swing.JTextField();
        txtNumero10 = new javax.swing.JTextField();
        txtNumero11 = new javax.swing.JTextField();
        txtNumero12 = new javax.swing.JTextField();
        txtNumero13 = new javax.swing.JTextField();
        txtNumero14 = new javax.swing.JTextField();
        txtNumero15 = new javax.swing.JTextField();
        txtNumero16 = new javax.swing.JTextField();
        txtNumero17 = new javax.swing.JTextField();
        txtNumero18 = new javax.swing.JTextField();
        txtNumero19 = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        lblDesignation = new javax.swing.JLabel();
        lblQuantite = new javax.swing.JLabel();
        lblPrixUnitaire = new javax.swing.JLabel();
        lblPrixTTC = new javax.swing.JLabel();
        txtPoidsNet = new javax.swing.JTextField();
        txtPoidsBrut = new javax.swing.JTextField();
        lblPoidsNet = new javax.swing.JLabel();
        lblPoidsBrut = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        lblPrenom = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        lblTelephone = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        lblAdresse = new javax.swing.JLabel();
        txtAdresse = new javax.swing.JTextField();
        lblCodePostal = new javax.swing.JLabel();
        txtCodePostal = new javax.swing.JTextField();
        lblVille = new javax.swing.JLabel();
        txtVille = new javax.swing.JTextField();
        lblPays = new javax.swing.JLabel();
        txtPays = new javax.swing.JTextField();
        btnCalculer = new javax.swing.JButton();
        txtNumeroFacture = new javax.swing.JTextField();
        lblNumeroFacture = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFichier = new javax.swing.JMenu();
        itemFermer = new javax.swing.JMenuItem();
        itemEnregistrer = new javax.swing.JMenuItem();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrixTTC19.setEditable(false);
        getContentPane().add(txtPrixTTC19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 90, -1));

        txtPrixTTC18.setEditable(false);
        getContentPane().add(txtPrixTTC18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 90, -1));

        txtPrixTTC17.setEditable(false);
        getContentPane().add(txtPrixTTC17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 90, -1));

        txtPrixTTC16.setEditable(false);
        getContentPane().add(txtPrixTTC16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 90, -1));

        txtPrixTTC15.setEditable(false);
        getContentPane().add(txtPrixTTC15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 90, -1));

        txtPrixTTC14.setEditable(false);
        getContentPane().add(txtPrixTTC14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 90, -1));

        txtPrixTTC13.setEditable(false);
        getContentPane().add(txtPrixTTC13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 90, -1));

        txtPrixTTC12.setEditable(false);
        getContentPane().add(txtPrixTTC12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 90, -1));

        txtPrixTTC11.setEditable(false);
        getContentPane().add(txtPrixTTC11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 90, -1));

        txtPrixTTC10.setEditable(false);
        getContentPane().add(txtPrixTTC10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 90, -1));

        txtPrixTTC9.setEditable(false);
        getContentPane().add(txtPrixTTC9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 90, -1));

        txtPrixTTC8.setEditable(false);
        getContentPane().add(txtPrixTTC8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 90, -1));

        txtPrixTTC7.setEditable(false);
        getContentPane().add(txtPrixTTC7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 90, -1));

        txtPrixTTC6.setEditable(false);
        getContentPane().add(txtPrixTTC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 90, -1));

        txtPrixTTC5.setEditable(false);
        getContentPane().add(txtPrixTTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 90, -1));

        txtPrixTTC4.setEditable(false);
        getContentPane().add(txtPrixTTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 90, -1));

        txtPrixTTC3.setEditable(false);
        getContentPane().add(txtPrixTTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 90, -1));

        txtPrixTTC2.setEditable(false);
        getContentPane().add(txtPrixTTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 90, -1));

        txtPrixTTC1.setEditable(false);
        getContentPane().add(txtPrixTTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 90, -1));

        txtPrixTTC0.setEditable(false);
        getContentPane().add(txtPrixTTC0, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 90, -1));

        txtPrixHT.setEditable(false);
        getContentPane().add(txtPrixHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 90, -1));

        txtTVA.setEditable(false);
        getContentPane().add(txtTVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 90, -1));

        lblTVA.setText("TVA");
        getContentPane().add(lblTVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 40, -1));

        lblPrixHT.setText("Prix HT");
        getContentPane().add(lblPrixHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 50, -1));

        txtPrixTTC.setEditable(false);
        getContentPane().add(txtPrixTTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 90, -1));

        lblTTC.setText("Prix TTC");
        getContentPane().add(lblTTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, -1, -1));

        txtPrixUnitaire0.setText("0");
        getContentPane().add(txtPrixUnitaire0, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 90, -1));

        txtPrixUnitaire1.setText("0");
        getContentPane().add(txtPrixUnitaire1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 90, -1));

        txtPrixUnitaire2.setText("0");
        getContentPane().add(txtPrixUnitaire2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 90, -1));

        txtPrixUnitaire3.setText("0");
        getContentPane().add(txtPrixUnitaire3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 90, -1));

        txtPrixUnitaire4.setText("0");
        getContentPane().add(txtPrixUnitaire4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 90, -1));

        txtPrixUnitaire5.setText("0");
        getContentPane().add(txtPrixUnitaire5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 90, -1));

        txtPrixUnitaire6.setText("0");
        getContentPane().add(txtPrixUnitaire6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 90, -1));

        txtPrixUnitaire7.setText("0");
        getContentPane().add(txtPrixUnitaire7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 90, -1));

        txtPrixUnitaire8.setText("0");
        getContentPane().add(txtPrixUnitaire8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 90, -1));

        txtPrixUnitaire9.setText("0");
        getContentPane().add(txtPrixUnitaire9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 90, -1));

        txtPrixUnitaire10.setText("0");
        getContentPane().add(txtPrixUnitaire10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 90, -1));

        txtPrixUnitaire11.setText("0");
        getContentPane().add(txtPrixUnitaire11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 90, -1));

        txtPrixUnitaire12.setText("0");
        getContentPane().add(txtPrixUnitaire12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 90, -1));

        txtPrixUnitaire13.setText("0");
        getContentPane().add(txtPrixUnitaire13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 90, -1));

        txtPrixUnitaire14.setText("0");
        getContentPane().add(txtPrixUnitaire14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 90, -1));

        txtPrixUnitaire15.setText("0");
        getContentPane().add(txtPrixUnitaire15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 90, -1));

        txtPrixUnitaire16.setText("0");
        getContentPane().add(txtPrixUnitaire16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 90, -1));

        txtPrixUnitaire17.setText("0");
        getContentPane().add(txtPrixUnitaire17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 90, -1));

        txtPrixUnitaire18.setText("0");
        getContentPane().add(txtPrixUnitaire18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 90, -1));

        txtPrixUnitaire19.setText("0");
        getContentPane().add(txtPrixUnitaire19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 90, -1));

        txtQte0.setText("0");
        getContentPane().add(txtQte0, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 60, -1));

        txtQte1.setText("0");
        getContentPane().add(txtQte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 60, -1));

        txtQte2.setText("0");
        getContentPane().add(txtQte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 60, -1));

        txtQte3.setText("0");
        getContentPane().add(txtQte3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 60, -1));

        txtQte4.setText("0");
        getContentPane().add(txtQte4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 60, -1));

        txtQte5.setText("0");
        getContentPane().add(txtQte5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 60, -1));

        txtQte6.setText("0");
        getContentPane().add(txtQte6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 60, -1));

        txtQte7.setText("0");
        getContentPane().add(txtQte7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 60, -1));

        txtQte8.setText("0");
        getContentPane().add(txtQte8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 60, -1));

        txtQte9.setText("0");
        getContentPane().add(txtQte9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 60, -1));

        txtQte10.setText("0");
        getContentPane().add(txtQte10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 60, -1));

        txtQte11.setText("0");
        getContentPane().add(txtQte11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 60, -1));

        txtQte12.setText("0");
        getContentPane().add(txtQte12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 60, -1));

        txtQte13.setText("0");
        getContentPane().add(txtQte13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 60, -1));

        txtQte14.setText("0");
        getContentPane().add(txtQte14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 60, -1));

        txtQte15.setText("0");
        getContentPane().add(txtQte15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 60, -1));

        txtQte16.setText("0");
        getContentPane().add(txtQte16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 60, -1));

        txtQte17.setText("0");
        getContentPane().add(txtQte17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 60, -1));

        txtQte18.setText("0");
        getContentPane().add(txtQte18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 60, -1));

        txtQte19.setText("0");
        getContentPane().add(txtQte19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 60, -1));

        getContentPane().add(txtDesignation0, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 390, -1));

        getContentPane().add(txtDesignation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 390, -1));

        getContentPane().add(txtDesignation2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 390, -1));

        getContentPane().add(txtDesignation3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 390, -1));

        getContentPane().add(txtDesignation4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 390, -1));

        getContentPane().add(txtDesignation5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 390, -1));

        getContentPane().add(txtDesignation6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 390, -1));

        getContentPane().add(txtDesignation7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 390, -1));

        getContentPane().add(txtDesignation8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 390, -1));

        getContentPane().add(txtDesignation9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 390, -1));

        getContentPane().add(txtDesignation10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 390, -1));

        getContentPane().add(txtDesignation11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 390, -1));

        getContentPane().add(txtDesignation12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 390, -1));

        getContentPane().add(txtDesignation13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 390, -1));

        getContentPane().add(txtDesignation14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 390, -1));

        getContentPane().add(txtDesignation15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 390, -1));

        getContentPane().add(txtDesignation16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 390, -1));

        getContentPane().add(txtDesignation17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 390, -1));

        getContentPane().add(txtDesignation18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 390, -1));

        getContentPane().add(txtDesignation19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 390, -1));

        getContentPane().add(txtNumero0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, -1));

        getContentPane().add(txtNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, -1));

        getContentPane().add(txtNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, -1));

        getContentPane().add(txtNumero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, -1));

        getContentPane().add(txtNumero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 90, -1));

        getContentPane().add(txtNumero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, -1));

        getContentPane().add(txtNumero6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, -1));

        getContentPane().add(txtNumero7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, -1));

        getContentPane().add(txtNumero8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 90, -1));

        getContentPane().add(txtNumero9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, -1));

        getContentPane().add(txtNumero10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 90, -1));

        getContentPane().add(txtNumero11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 90, -1));

        getContentPane().add(txtNumero12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 90, -1));

        getContentPane().add(txtNumero13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 90, -1));

        getContentPane().add(txtNumero14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 90, -1));

        getContentPane().add(txtNumero15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 90, -1));

        getContentPane().add(txtNumero16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 90, -1));

        getContentPane().add(txtNumero17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 90, -1));

        getContentPane().add(txtNumero18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 90, -1));

        getContentPane().add(txtNumero19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 90, -1));

        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setText("Num\u00e9ro");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, -1));

        lblDesignation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesignation.setText("D\u00e9signation");
        getContentPane().add(lblDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 390, -1));

        lblQuantite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantite.setText("Quantit\u00e9");
        getContentPane().add(lblQuantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 60, -1));

        lblPrixUnitaire.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrixUnitaire.setText("Prix unitaire");
        getContentPane().add(lblPrixUnitaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 90, -1));

        lblPrixTTC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrixTTC.setText("Prix TTC");
        getContentPane().add(lblPrixTTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 90, -1));

        txtPoidsNet.setText("0");
        getContentPane().add(txtPoidsNet, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 90, -1));

        txtPoidsBrut.setText("0");
        getContentPane().add(txtPoidsBrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 90, -1));

        lblPoidsNet.setText("Poids net");
        getContentPane().add(lblPoidsNet, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, -1, -1));

        lblPoidsBrut.setText("Poids Brut");
        getContentPane().add(lblPoidsBrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, -1, -1));

        lblNom.setText("Nom :");
        getContentPane().add(lblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, -1));

        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, -1));

        lblPrenom.setText("Prenom :");
        getContentPane().add(lblPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 80, -1));

        getContentPane().add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 230, -1));

        lblTelephone.setText("T\u00e9l\u00e9phone :");
        getContentPane().add(lblTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        lblFax.setText("Fax :");
        getContentPane().add(lblFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, -1));

        getContentPane().add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 180, -1));

        getContentPane().add(txtFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 180, -1));

        lblAdresse.setText("Adresse :");
        getContentPane().add(lblAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        getContentPane().add(txtAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 470, -1));

        lblCodePostal.setText("Code postal :");
        getContentPane().add(lblCodePostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        getContentPane().add(txtCodePostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, -1));

        lblVille.setText("Ville :");
        getContentPane().add(lblVille, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        getContentPane().add(txtVille, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 190, -1));

        lblPays.setText("Pays :");
        getContentPane().add(lblPays, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        getContentPane().add(txtPays, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 190, -1));

        btnCalculer.setText("Calculer");
        btnCalculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculerActionPerformed(evt);
            }
        });

        getContentPane().add(btnCalculer, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 90, -1));

        getContentPane().add(txtNumeroFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 90, -1));

        lblNumeroFacture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroFacture.setText("N\u00b0 Facture");
        getContentPane().add(lblNumeroFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 90, -1));

        menuFichier.setText("Fichier");
        itemFermer.setText("Fermer");
        itemFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFermerActionPerformed(evt);
            }
        });

        menuFichier.add(itemFermer);

        itemEnregistrer.setText("Enregistrer");
        itemEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEnregistrerActionPerformed(evt);
            }
        });

        menuFichier.add(itemEnregistrer);

        jMenuBar1.add(menuFichier);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 900, 600);
    }//GEN-END:initComponents

    private void itemEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEnregistrerActionPerformed
        //JOptionPane.showMessageDialog (this, "Logiciel développé Par Olivier \n version: 1.0","A propos",JOptionPane.INFORMATION_MESSAGE);
        if(txtNom.getText().equals("")){
            JOptionPane.showMessageDialog (this, "Vous devez saisir un nom","Erreur de saisie",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(txtPrenom.getText().equals("")){
            JOptionPane.showMessageDialog (this, "Vous devez saisir un prénom","Erreur de saisie",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(txtTelephone.getText().equals("")){
            JOptionPane.showMessageDialog (this, "Vous devez saisir un numero de telephone","Erreur de saisie",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(txtAdresse.getText().equals("")){
            JOptionPane.showMessageDialog (this, "Vous devez saisir une adresse","Erreur de saisie",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(txtCodePostal.getText().equals("")){
            JOptionPane.showMessageDialog (this, "Vous devez saisir un code postal","Erreur de saisie",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(txtVille.getText().equals("")){
            JOptionPane.showMessageDialog (this, "Vous devez saisir une ville","Erreur de saisie",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(txtPays.getText().equals("")){
            JOptionPane.showMessageDialog (this, "Vous devez saisir un pays","Erreur de saisie",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            String nom = txtNom.getText();
            String prenom = txtPrenom.getText();
            String adresse =  txtAdresse.getText();
            String codePostal = txtCodePostal.getText();
            String ville = txtVille.getText();
            String pays = txtPays.getText();
            String telephone = txtTelephone.getText();
            String fax = txtFax.getText();
            String numeroFacture = txtNumeroFacture.getText();
            
            String[] numero = new String[20];
            numero[0] = txtNumero0.getText(); 
            numero[1] = txtNumero1.getText();
            numero[2] = txtNumero2.getText();
            numero[3] = txtNumero3.getText();
            numero[4] = txtNumero4.getText();
            numero[5] = txtNumero5.getText();
            numero[6] = txtNumero6.getText();
            numero[7] = txtNumero7.getText();
            numero[8] = txtNumero8.getText();
            numero[9] = txtNumero9.getText();
            numero[10] = txtNumero10.getText();
            numero[11] = txtNumero11.getText();
            numero[12] = txtNumero12.getText();
            numero[13] = txtNumero13.getText();
            numero[14] = txtNumero14.getText();
            numero[15] = txtNumero15.getText();
            numero[16] = txtNumero16.getText();
            numero[17] = txtNumero17.getText();
            numero[18] = txtNumero18.getText();
            numero[19] = txtNumero19.getText();
        
            String[] designation = new String[20];
            designation[0] = txtDesignation0.getText();
            designation[1] = txtDesignation1.getText();
            designation[2] = txtDesignation2.getText();
            designation[3] = txtDesignation3.getText();
            designation[4] = txtDesignation4.getText();
            designation[5] = txtDesignation5.getText();
            designation[6] = txtDesignation6.getText();
            designation[7] = txtDesignation7.getText();
            designation[8] = txtDesignation8.getText();
            designation[9] = txtDesignation9.getText();
            designation[10] = txtDesignation10.getText();
            designation[11] = txtDesignation11.getText();
            designation[12] = txtDesignation12.getText();
            designation[13] = txtDesignation13.getText();
            designation[14] = txtDesignation14.getText();
            designation[15] = txtDesignation15.getText();
            designation[16] = txtDesignation16.getText();
            designation[17] = txtDesignation17.getText();
            designation[18] = txtDesignation18.getText();
            designation[19] = txtDesignation19.getText();
        
            double[] qte = new double[20];
            qte[0] = Double.parseDouble(txtQte0.getText());
            qte[1] = Double.parseDouble(txtQte1.getText());
            qte[2] = Double.parseDouble(txtQte2.getText());
            qte[3] = Double.parseDouble(txtQte3.getText());
            qte[4] = Double.parseDouble(txtQte4.getText());
            qte[5] = Double.parseDouble(txtQte5.getText());
            qte[6] = Double.parseDouble(txtQte6.getText());
            qte[7] = Double.parseDouble(txtQte7.getText());
            qte[8] = Double.parseDouble(txtQte8.getText());
            qte[9] = Double.parseDouble(txtQte9.getText());
            qte[10] = Double.parseDouble(txtQte10.getText());
            qte[11] = Double.parseDouble(txtQte11.getText());
            qte[12] = Double.parseDouble(txtQte12.getText());
            qte[13] = Double.parseDouble(txtQte13.getText());
            qte[14] = Double.parseDouble(txtQte14.getText());
            qte[15] = Double.parseDouble(txtQte15.getText());
            qte[16] = Double.parseDouble(txtQte16.getText());
            qte[17] = Double.parseDouble(txtQte17.getText());
            qte[18] = Double.parseDouble(txtQte18.getText());
            qte[19] = Double.parseDouble(txtQte19.getText());
        
            double[] prixUnitaire = new double[20];
            prixUnitaire[0] = Double.parseDouble(txtPrixUnitaire0.getText());
            prixUnitaire[1] = Double.parseDouble(txtPrixUnitaire1.getText());
            prixUnitaire[2] = Double.parseDouble(txtPrixUnitaire2.getText());
            prixUnitaire[3] = Double.parseDouble(txtPrixUnitaire3.getText());
            prixUnitaire[4] = Double.parseDouble(txtPrixUnitaire4.getText());
            prixUnitaire[5] = Double.parseDouble(txtPrixUnitaire5.getText());
            prixUnitaire[6] = Double.parseDouble(txtPrixUnitaire6.getText());
            prixUnitaire[7] = Double.parseDouble(txtPrixUnitaire7.getText());
            prixUnitaire[8] = Double.parseDouble(txtPrixUnitaire8.getText());
            prixUnitaire[9] = Double.parseDouble(txtPrixUnitaire9.getText());
            prixUnitaire[10] = Double.parseDouble(txtPrixUnitaire10.getText());
            prixUnitaire[11] = Double.parseDouble(txtPrixUnitaire11.getText());
            prixUnitaire[12] = Double.parseDouble(txtPrixUnitaire12.getText());
            prixUnitaire[13] = Double.parseDouble(txtPrixUnitaire13.getText());
            prixUnitaire[14] = Double.parseDouble(txtPrixUnitaire14.getText());
            prixUnitaire[15] = Double.parseDouble(txtPrixUnitaire15.getText());
            prixUnitaire[16] = Double.parseDouble(txtPrixUnitaire16.getText());
            prixUnitaire[17] = Double.parseDouble(txtPrixUnitaire17.getText());
            prixUnitaire[18] = Double.parseDouble(txtPrixUnitaire18.getText());
            prixUnitaire[19] = Double.parseDouble(txtPrixUnitaire19.getText());
            
            double[] prixTTC = new double[20];
            prixTTC[0] = Double.parseDouble(txtPrixTTC0.getText());
            prixTTC[1] = Double.parseDouble(txtPrixTTC1.getText());
            prixTTC[2] = Double.parseDouble(txtPrixTTC2.getText());
            prixTTC[3] = Double.parseDouble(txtPrixTTC3.getText());
            prixTTC[4] = Double.parseDouble(txtPrixTTC4.getText());
            prixTTC[5] = Double.parseDouble(txtPrixTTC5.getText());
            prixTTC[6] = Double.parseDouble(txtPrixTTC6.getText());
            prixTTC[7] = Double.parseDouble(txtPrixTTC7.getText());
            prixTTC[8] = Double.parseDouble(txtPrixTTC8.getText());
            prixTTC[9] = Double.parseDouble(txtPrixTTC9.getText());
            prixTTC[10] = Double.parseDouble(txtPrixTTC10.getText());
            prixTTC[11] = Double.parseDouble(txtPrixTTC11.getText());
            prixTTC[12] = Double.parseDouble(txtPrixTTC12.getText());
            prixTTC[13] = Double.parseDouble(txtPrixTTC13.getText());
            prixTTC[14] = Double.parseDouble(txtPrixTTC14.getText());
            prixTTC[15] = Double.parseDouble(txtPrixTTC15.getText());
            prixTTC[16] = Double.parseDouble(txtPrixTTC16.getText());
            prixTTC[17] = Double.parseDouble(txtPrixTTC17.getText());
            prixTTC[18] = Double.parseDouble(txtPrixTTC18.getText());
            prixTTC[19] = Double.parseDouble(txtPrixTTC19.getText());
            
            double total_TTC = ttc; 
            double valeur_TVA = tva; 
            double total_HT = ht; 
        
            cee = new Facture_CEE(nom, prenom, adresse, codePostal, ville, pays, telephone, fax, numeroFacture,
            numero, designation, qte, prixUnitaire, prixTTC,
            100, 100, total_TTC, valeur_TVA, total_HT);
            
            boolean retour = Acceuil.baseDeDonneeFacture.Enregistrer(cee, numeroFacture);
            if(retour == true){
                JOptionPane.showMessageDialog (this, "Super","OK",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog (this, "La facture existe déjà","Erreur",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_itemEnregistrerActionPerformed

    private void itemFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFermerActionPerformed
        dispose();
    }//GEN-LAST:event_itemFermerActionPerformed

    private void btnCalculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculerActionPerformed
        String nom = txtNom.getText();
        String prenom = txtPrenom.getText();
        String adresse =  txtAdresse.getText();
        String codePostal = txtCodePostal.getText();
        String ville = txtVille.getText();
        String pays = txtPays.getText();
        String telephone = txtTelephone.getText();
        String fax = txtFax.getText();
        String numeroFacture = txtNumeroFacture.getText();
        
        String[] numero = new String[20];
        numero[0] = txtNumero0.getText(); 
        numero[1] = txtNumero1.getText();
        numero[2] = txtNumero2.getText();
        numero[3] = txtNumero3.getText();
        numero[4] = txtNumero4.getText();
        numero[5] = txtNumero5.getText();
        numero[6] = txtNumero6.getText();
        numero[7] = txtNumero7.getText();
        numero[8] = txtNumero8.getText();
        numero[9] = txtNumero9.getText();
        numero[10] = txtNumero10.getText();
        numero[11] = txtNumero11.getText();
        numero[12] = txtNumero12.getText();
        numero[13] = txtNumero13.getText();
        numero[14] = txtNumero14.getText();
        numero[15] = txtNumero15.getText();
        numero[16] = txtNumero16.getText();
        numero[17] = txtNumero17.getText();
        numero[18] = txtNumero18.getText();
        numero[19] = txtNumero19.getText();
        
        String[] designation = new String[20];
        designation[0] = txtDesignation0.getText();
        designation[1] = txtDesignation1.getText();
        designation[2] = txtDesignation2.getText();
        designation[3] = txtDesignation3.getText();
        designation[4] = txtDesignation4.getText();
        designation[5] = txtDesignation5.getText();
        designation[6] = txtDesignation6.getText();
        designation[7] = txtDesignation7.getText();
        designation[8] = txtDesignation8.getText();
        designation[9] = txtDesignation9.getText();
        designation[10] = txtDesignation10.getText();
        designation[11] = txtDesignation11.getText();
        designation[12] = txtDesignation12.getText();
        designation[13] = txtDesignation13.getText();
        designation[14] = txtDesignation14.getText();
        designation[15] = txtDesignation15.getText();
        designation[16] = txtDesignation16.getText();
        designation[17] = txtDesignation17.getText();
        designation[18] = txtDesignation18.getText();
        designation[19] = txtDesignation19.getText();
        
        double[] qte = new double[20];
        qte[0] = Double.parseDouble(txtQte0.getText());
        qte[1] = Double.parseDouble(txtQte1.getText());
        qte[2] = Double.parseDouble(txtQte2.getText());
        qte[3] = Double.parseDouble(txtQte3.getText());
        qte[4] = Double.parseDouble(txtQte4.getText());
        qte[5] = Double.parseDouble(txtQte5.getText());
        qte[6] = Double.parseDouble(txtQte6.getText());
        qte[7] = Double.parseDouble(txtQte7.getText());
        qte[8] = Double.parseDouble(txtQte8.getText());
        qte[9] = Double.parseDouble(txtQte9.getText());
        qte[10] = Double.parseDouble(txtQte10.getText());
        qte[11] = Double.parseDouble(txtQte11.getText());
        qte[12] = Double.parseDouble(txtQte12.getText());
        qte[13] = Double.parseDouble(txtQte13.getText());
        qte[14] = Double.parseDouble(txtQte14.getText());
        qte[15] = Double.parseDouble(txtQte15.getText());
        qte[16] = Double.parseDouble(txtQte16.getText());
        qte[17] = Double.parseDouble(txtQte17.getText());
        qte[18] = Double.parseDouble(txtQte18.getText());
        qte[19] = Double.parseDouble(txtQte19.getText());
        
        double[] prixUnitaire = new double[20];
        prixUnitaire[0] = Double.parseDouble(txtPrixUnitaire0.getText());
        prixUnitaire[1] = Double.parseDouble(txtPrixUnitaire1.getText());
        prixUnitaire[2] = Double.parseDouble(txtPrixUnitaire2.getText());
        prixUnitaire[3] = Double.parseDouble(txtPrixUnitaire3.getText());
        prixUnitaire[4] = Double.parseDouble(txtPrixUnitaire4.getText());
        prixUnitaire[5] = Double.parseDouble(txtPrixUnitaire5.getText());
        prixUnitaire[6] = Double.parseDouble(txtPrixUnitaire6.getText());
        prixUnitaire[7] = Double.parseDouble(txtPrixUnitaire7.getText());
        prixUnitaire[8] = Double.parseDouble(txtPrixUnitaire8.getText());
        prixUnitaire[9] = Double.parseDouble(txtPrixUnitaire9.getText());
        prixUnitaire[10] = Double.parseDouble(txtPrixUnitaire10.getText());
        prixUnitaire[11] = Double.parseDouble(txtPrixUnitaire11.getText());
        prixUnitaire[12] = Double.parseDouble(txtPrixUnitaire12.getText());
        prixUnitaire[13] = Double.parseDouble(txtPrixUnitaire13.getText());
        prixUnitaire[14] = Double.parseDouble(txtPrixUnitaire14.getText());
        prixUnitaire[15] = Double.parseDouble(txtPrixUnitaire15.getText());
        prixUnitaire[16] = Double.parseDouble(txtPrixUnitaire16.getText());
        prixUnitaire[17] = Double.parseDouble(txtPrixUnitaire17.getText());
        prixUnitaire[18] = Double.parseDouble(txtPrixUnitaire18.getText());
        prixUnitaire[19] = Double.parseDouble(txtPrixUnitaire19.getText());
        double[] prixTTC = new double[20];
        for(int i = 0; i < 20; i++){
            prixTTC[i] = 0.0;
        }
        
        Facture ceeCalcul = new Facture_CEE(nom, prenom, adresse, codePostal, ville, pays, telephone, fax, numeroFacture,
    numero, designation, qte, prixUnitaire, prixTTC,
    100, 100, 0, 0, 0);
        
        double[] calcul = new double[23];
        calcul = ceeCalcul.Calculer();
        
        NumberFormat nf = NumberFormat.getInstance();
        nf.setMaximumFractionDigits(2);
        
        txtPrixTTC0.setText(String.valueOf(calcul[0]));
        txtPrixTTC1.setText(String.valueOf(calcul[1]));
        txtPrixTTC2.setText(String.valueOf(calcul[2]));
        txtPrixTTC3.setText(String.valueOf(calcul[3]));
        txtPrixTTC4.setText(String.valueOf(calcul[4]));
        txtPrixTTC5.setText(String.valueOf(calcul[5]));
        txtPrixTTC6.setText(String.valueOf(calcul[6]));
        txtPrixTTC7.setText(String.valueOf(calcul[7]));
        txtPrixTTC8.setText(String.valueOf(calcul[8]));
        txtPrixTTC9.setText(String.valueOf(calcul[9]));
        txtPrixTTC10.setText(String.valueOf(calcul[10]));
        txtPrixTTC11.setText(String.valueOf(calcul[11]));
        txtPrixTTC12.setText(String.valueOf(calcul[12]));
        txtPrixTTC13.setText(String.valueOf(calcul[13]));
        txtPrixTTC14.setText(String.valueOf(calcul[14]));
        txtPrixTTC15.setText(String.valueOf(calcul[15]));
        txtPrixTTC16.setText(String.valueOf(calcul[16]));
        txtPrixTTC17.setText(String.valueOf(calcul[17]));
        txtPrixTTC18.setText(String.valueOf(calcul[18]));
        txtPrixTTC19.setText(String.valueOf(calcul[19]));
        
        ttc = calcul[20];
        txtPrixTTC.setText(nf.format(calcul[20]));
        
        tva = calcul[21];
        txtTVA.setText(nf.format(calcul[21]));
  
        ht = calcul[22];
        txtPrixHT.setText(nf.format(calcul[22]));
    }//GEN-LAST:event_btnCalculerActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculer;
    private javax.swing.JMenuItem itemEnregistrer;
    private javax.swing.JMenuItem itemFermer;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAdresse;
    private javax.swing.JLabel lblCodePostal;
    private javax.swing.JLabel lblDesignation;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroFacture;
    private javax.swing.JLabel lblPays;
    private javax.swing.JLabel lblPoidsBrut;
    private javax.swing.JLabel lblPoidsNet;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JLabel lblPrixHT;
    private javax.swing.JLabel lblPrixTTC;
    private javax.swing.JLabel lblPrixUnitaire;
    private javax.swing.JLabel lblQuantite;
    private javax.swing.JLabel lblTTC;
    private javax.swing.JLabel lblTVA;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblVille;
    private javax.swing.JMenu menuFichier;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtCodePostal;
    private javax.swing.JTextField txtDesignation0;
    private javax.swing.JTextField txtDesignation1;
    private javax.swing.JTextField txtDesignation10;
    private javax.swing.JTextField txtDesignation11;
    private javax.swing.JTextField txtDesignation12;
    private javax.swing.JTextField txtDesignation13;
    private javax.swing.JTextField txtDesignation14;
    private javax.swing.JTextField txtDesignation15;
    private javax.swing.JTextField txtDesignation16;
    private javax.swing.JTextField txtDesignation17;
    private javax.swing.JTextField txtDesignation18;
    private javax.swing.JTextField txtDesignation19;
    private javax.swing.JTextField txtDesignation2;
    private javax.swing.JTextField txtDesignation3;
    private javax.swing.JTextField txtDesignation4;
    private javax.swing.JTextField txtDesignation5;
    private javax.swing.JTextField txtDesignation6;
    private javax.swing.JTextField txtDesignation7;
    private javax.swing.JTextField txtDesignation8;
    private javax.swing.JTextField txtDesignation9;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumero0;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero10;
    private javax.swing.JTextField txtNumero11;
    private javax.swing.JTextField txtNumero12;
    private javax.swing.JTextField txtNumero13;
    private javax.swing.JTextField txtNumero14;
    private javax.swing.JTextField txtNumero15;
    private javax.swing.JTextField txtNumero16;
    private javax.swing.JTextField txtNumero17;
    private javax.swing.JTextField txtNumero18;
    private javax.swing.JTextField txtNumero19;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextField txtNumero3;
    private javax.swing.JTextField txtNumero4;
    private javax.swing.JTextField txtNumero5;
    private javax.swing.JTextField txtNumero6;
    private javax.swing.JTextField txtNumero7;
    private javax.swing.JTextField txtNumero8;
    private javax.swing.JTextField txtNumero9;
    private javax.swing.JTextField txtNumeroFacture;
    private javax.swing.JTextField txtPays;
    private javax.swing.JTextField txtPoidsBrut;
    private javax.swing.JTextField txtPoidsNet;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtPrixHT;
    private javax.swing.JTextField txtPrixTTC;
    private javax.swing.JTextField txtPrixTTC0;
    private javax.swing.JTextField txtPrixTTC1;
    private javax.swing.JTextField txtPrixTTC10;
    private javax.swing.JTextField txtPrixTTC11;
    private javax.swing.JTextField txtPrixTTC12;
    private javax.swing.JTextField txtPrixTTC13;
    private javax.swing.JTextField txtPrixTTC14;
    private javax.swing.JTextField txtPrixTTC15;
    private javax.swing.JTextField txtPrixTTC16;
    private javax.swing.JTextField txtPrixTTC17;
    private javax.swing.JTextField txtPrixTTC18;
    private javax.swing.JTextField txtPrixTTC19;
    private javax.swing.JTextField txtPrixTTC2;
    private javax.swing.JTextField txtPrixTTC3;
    private javax.swing.JTextField txtPrixTTC4;
    private javax.swing.JTextField txtPrixTTC5;
    private javax.swing.JTextField txtPrixTTC6;
    private javax.swing.JTextField txtPrixTTC7;
    private javax.swing.JTextField txtPrixTTC8;
    private javax.swing.JTextField txtPrixTTC9;
    private javax.swing.JTextField txtPrixUnitaire0;
    private javax.swing.JTextField txtPrixUnitaire1;
    private javax.swing.JTextField txtPrixUnitaire10;
    private javax.swing.JTextField txtPrixUnitaire11;
    private javax.swing.JTextField txtPrixUnitaire12;
    private javax.swing.JTextField txtPrixUnitaire13;
    private javax.swing.JTextField txtPrixUnitaire14;
    private javax.swing.JTextField txtPrixUnitaire15;
    private javax.swing.JTextField txtPrixUnitaire16;
    private javax.swing.JTextField txtPrixUnitaire17;
    private javax.swing.JTextField txtPrixUnitaire18;
    private javax.swing.JTextField txtPrixUnitaire19;
    private javax.swing.JTextField txtPrixUnitaire2;
    private javax.swing.JTextField txtPrixUnitaire3;
    private javax.swing.JTextField txtPrixUnitaire4;
    private javax.swing.JTextField txtPrixUnitaire5;
    private javax.swing.JTextField txtPrixUnitaire6;
    private javax.swing.JTextField txtPrixUnitaire7;
    private javax.swing.JTextField txtPrixUnitaire8;
    private javax.swing.JTextField txtPrixUnitaire9;
    private javax.swing.JTextField txtQte0;
    private javax.swing.JTextField txtQte1;
    private javax.swing.JTextField txtQte10;
    private javax.swing.JTextField txtQte11;
    private javax.swing.JTextField txtQte12;
    private javax.swing.JTextField txtQte13;
    private javax.swing.JTextField txtQte14;
    private javax.swing.JTextField txtQte15;
    private javax.swing.JTextField txtQte16;
    private javax.swing.JTextField txtQte17;
    private javax.swing.JTextField txtQte18;
    private javax.swing.JTextField txtQte19;
    private javax.swing.JTextField txtQte2;
    private javax.swing.JTextField txtQte3;
    private javax.swing.JTextField txtQte4;
    private javax.swing.JTextField txtQte5;
    private javax.swing.JTextField txtQte6;
    private javax.swing.JTextField txtQte7;
    private javax.swing.JTextField txtQte8;
    private javax.swing.JTextField txtQte9;
    private javax.swing.JTextField txtTVA;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtVille;
    // End of variables declaration//GEN-END:variables
    
}
