import java.awt.*;
import java.awt.event.*;
import java.io.*;
import javax.swing.*;
import java.text.*;
import java.util.*;
/*
 * Rechercher_Facture_Cee.java
 *
 * Created on 4 décembre 2005, 21:28
 */

/**
 *
 * @author  Sébastien
 */
public class Rechercher_Facture extends javax.swing.JInternalFrame {
    boolean modif;
    private ArrayList retour;
    int i = -1;
    /** Creates new form Rechercher_Facture_Cee */
    public Rechercher_Facture() {
        initComponents();
        String[] champsRecherche = {"Nom", "Prénom", "Numéro facture"};
        for (int i = 0 ; i < champsRecherche.length ; i++)
	{
            cmboRecherche.addItem(champsRecherche[i]);
	}
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        btngCeeOuExport = new javax.swing.ButtonGroup();
        txtPrixTTC19 = new javax.swing.JTextField();
        txtPrixTTC18 = new javax.swing.JTextField();
        txtPrixTTC17 = new javax.swing.JTextField();
        txtPrixTTC16 = new javax.swing.JTextField();
        txtPrixTTC15 = new javax.swing.JTextField();
        txtPrixTTC14 = new javax.swing.JTextField();
        txtPrixTTC13 = new javax.swing.JTextField();
        txtPrixTTC12 = new javax.swing.JTextField();
        txtPrixTTC11 = new javax.swing.JTextField();
        txtPrixTTC10 = new javax.swing.JTextField();
        txtPrixTTC9 = new javax.swing.JTextField();
        txtPrixTTC8 = new javax.swing.JTextField();
        txtPrixTTC7 = new javax.swing.JTextField();
        txtPrixTTC6 = new javax.swing.JTextField();
        txtPrixTTC5 = new javax.swing.JTextField();
        txtPrixTTC4 = new javax.swing.JTextField();
        txtPrixTTC3 = new javax.swing.JTextField();
        txtPrixTTC2 = new javax.swing.JTextField();
        txtPrixTTC1 = new javax.swing.JTextField();
        txtPrixTTC0 = new javax.swing.JTextField();
        txtPrixUnitaire0 = new javax.swing.JTextField();
        txtPrixUnitaire1 = new javax.swing.JTextField();
        txtPrixUnitaire2 = new javax.swing.JTextField();
        txtPrixUnitaire3 = new javax.swing.JTextField();
        txtPrixUnitaire4 = new javax.swing.JTextField();
        txtPrixUnitaire5 = new javax.swing.JTextField();
        txtPrixUnitaire6 = new javax.swing.JTextField();
        txtPrixUnitaire7 = new javax.swing.JTextField();
        txtPrixUnitaire8 = new javax.swing.JTextField();
        txtPrixUnitaire9 = new javax.swing.JTextField();
        txtPrixUnitaire10 = new javax.swing.JTextField();
        txtPrixUnitaire11 = new javax.swing.JTextField();
        txtPrixUnitaire12 = new javax.swing.JTextField();
        txtPrixUnitaire13 = new javax.swing.JTextField();
        txtPrixUnitaire14 = new javax.swing.JTextField();
        txtPrixUnitaire15 = new javax.swing.JTextField();
        txtPrixUnitaire16 = new javax.swing.JTextField();
        txtPrixUnitaire17 = new javax.swing.JTextField();
        txtPrixUnitaire18 = new javax.swing.JTextField();
        txtPrixUnitaire19 = new javax.swing.JTextField();
        txtQte0 = new javax.swing.JTextField();
        txtQte1 = new javax.swing.JTextField();
        txtQte2 = new javax.swing.JTextField();
        txtQte3 = new javax.swing.JTextField();
        txtQte4 = new javax.swing.JTextField();
        txtQte5 = new javax.swing.JTextField();
        txtQte6 = new javax.swing.JTextField();
        txtQte7 = new javax.swing.JTextField();
        txtQte8 = new javax.swing.JTextField();
        txtQte9 = new javax.swing.JTextField();
        txtQte10 = new javax.swing.JTextField();
        txtQte11 = new javax.swing.JTextField();
        txtQte12 = new javax.swing.JTextField();
        txtQte13 = new javax.swing.JTextField();
        txtQte14 = new javax.swing.JTextField();
        txtQte15 = new javax.swing.JTextField();
        txtQte16 = new javax.swing.JTextField();
        txtQte17 = new javax.swing.JTextField();
        txtQte18 = new javax.swing.JTextField();
        txtQte19 = new javax.swing.JTextField();
        txtDesignation0 = new javax.swing.JTextField();
        txtDesignation1 = new javax.swing.JTextField();
        txtDesignation2 = new javax.swing.JTextField();
        txtDesignation3 = new javax.swing.JTextField();
        txtDesignation4 = new javax.swing.JTextField();
        txtDesignation5 = new javax.swing.JTextField();
        txtDesignation6 = new javax.swing.JTextField();
        txtDesignation7 = new javax.swing.JTextField();
        txtDesignation8 = new javax.swing.JTextField();
        txtDesignation9 = new javax.swing.JTextField();
        txtDesignation10 = new javax.swing.JTextField();
        txtDesignation11 = new javax.swing.JTextField();
        txtDesignation12 = new javax.swing.JTextField();
        txtDesignation13 = new javax.swing.JTextField();
        txtDesignation14 = new javax.swing.JTextField();
        txtDesignation15 = new javax.swing.JTextField();
        txtDesignation16 = new javax.swing.JTextField();
        txtDesignation17 = new javax.swing.JTextField();
        txtDesignation18 = new javax.swing.JTextField();
        txtDesignation19 = new javax.swing.JTextField();
        txtNumero0 = new javax.swing.JTextField();
        txtNumero1 = new javax.swing.JTextField();
        txtNumero2 = new javax.swing.JTextField();
        txtNumero3 = new javax.swing.JTextField();
        txtNumero4 = new javax.swing.JTextField();
        txtNumero5 = new javax.swing.JTextField();
        txtNumero6 = new javax.swing.JTextField();
        txtNumero7 = new javax.swing.JTextField();
        txtNumero8 = new javax.swing.JTextField();
        txtNumero9 = new javax.swing.JTextField();
        txtNumero10 = new javax.swing.JTextField();
        txtNumero11 = new javax.swing.JTextField();
        txtNumero12 = new javax.swing.JTextField();
        txtNumero13 = new javax.swing.JTextField();
        txtNumero14 = new javax.swing.JTextField();
        txtNumero15 = new javax.swing.JTextField();
        txtNumero16 = new javax.swing.JTextField();
        txtNumero17 = new javax.swing.JTextField();
        txtNumero18 = new javax.swing.JTextField();
        txtNumero19 = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        lblDesignation = new javax.swing.JLabel();
        lblQuantite = new javax.swing.JLabel();
        lblPrixUnitaire = new javax.swing.JLabel();
        lblPrixTTC = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        lblPrenom = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        lblTelephone = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        lblAdresse = new javax.swing.JLabel();
        txtAdresse = new javax.swing.JTextField();
        lblCodePostal = new javax.swing.JLabel();
        txtCodePostal = new javax.swing.JTextField();
        lblVille = new javax.swing.JLabel();
        txtVille = new javax.swing.JTextField();
        lblPays = new javax.swing.JLabel();
        txtPays = new javax.swing.JTextField();
        btnCalculer = new javax.swing.JButton();
        cmboRecherche = new javax.swing.JComboBox();
        txtRecherche = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        rbtnCee = new javax.swing.JRadioButton();
        rbtnExport = new javax.swing.JRadioButton();
        lblPrixHTOuPoidsBrut = new javax.swing.JLabel();
        lblRemiseOuTVA = new javax.swing.JLabel();
        lblTVAOuPoidsNet = new javax.swing.JLabel();
        txtPrixTTC = new javax.swing.JTextField();
        txtPrixHTOuPoidsBrut = new javax.swing.JTextField();
        txtTVAOuPoidsNet = new javax.swing.JTextField();
        txtPrixTTCApresOuPrixHT = new javax.swing.JTextField();
        lblTTCRemiseOuHT = new javax.swing.JLabel();
        txtRemiseOuTVA = new javax.swing.JTextField();
        lblTTC = new javax.swing.JLabel();
        txtNumeroFacture = new javax.swing.JTextField();
        lblNumeroFacture = new javax.swing.JLabel();
        btnPrecedent = new javax.swing.JButton();
        btnSuivant = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFichier = new javax.swing.JMenu();
        itemFermer = new javax.swing.JMenuItem();
        menuEdition = new javax.swing.JMenu();
        itemModifier = new javax.swing.JMenuItem();
        itemSupprimer = new javax.swing.JMenuItem();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrixTTC19.setEditable(false);
        getContentPane().add(txtPrixTTC19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 90, -1));

        txtPrixTTC18.setEditable(false);
        getContentPane().add(txtPrixTTC18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 90, -1));

        txtPrixTTC17.setEditable(false);
        getContentPane().add(txtPrixTTC17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 90, -1));

        txtPrixTTC16.setEditable(false);
        getContentPane().add(txtPrixTTC16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 90, -1));

        txtPrixTTC15.setEditable(false);
        getContentPane().add(txtPrixTTC15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 90, -1));

        txtPrixTTC14.setEditable(false);
        getContentPane().add(txtPrixTTC14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 90, -1));

        txtPrixTTC13.setEditable(false);
        getContentPane().add(txtPrixTTC13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 90, -1));

        txtPrixTTC12.setEditable(false);
        getContentPane().add(txtPrixTTC12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 90, -1));

        txtPrixTTC11.setEditable(false);
        getContentPane().add(txtPrixTTC11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 90, -1));

        txtPrixTTC10.setEditable(false);
        getContentPane().add(txtPrixTTC10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 90, -1));

        txtPrixTTC9.setEditable(false);
        getContentPane().add(txtPrixTTC9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 90, -1));

        txtPrixTTC8.setEditable(false);
        getContentPane().add(txtPrixTTC8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 90, -1));

        txtPrixTTC7.setEditable(false);
        getContentPane().add(txtPrixTTC7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 90, -1));

        txtPrixTTC6.setEditable(false);
        getContentPane().add(txtPrixTTC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 90, -1));

        txtPrixTTC5.setEditable(false);
        getContentPane().add(txtPrixTTC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 90, -1));

        txtPrixTTC4.setEditable(false);
        getContentPane().add(txtPrixTTC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 90, -1));

        txtPrixTTC3.setEditable(false);
        getContentPane().add(txtPrixTTC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 90, -1));

        txtPrixTTC2.setEditable(false);
        getContentPane().add(txtPrixTTC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 90, -1));

        txtPrixTTC1.setEditable(false);
        getContentPane().add(txtPrixTTC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 90, -1));

        txtPrixTTC0.setEditable(false);
        getContentPane().add(txtPrixTTC0, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 90, -1));

        txtPrixUnitaire0.setEditable(false);
        txtPrixUnitaire0.setText("0");
        getContentPane().add(txtPrixUnitaire0, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 90, -1));

        txtPrixUnitaire1.setEditable(false);
        txtPrixUnitaire1.setText("0");
        getContentPane().add(txtPrixUnitaire1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 90, -1));

        txtPrixUnitaire2.setEditable(false);
        txtPrixUnitaire2.setText("0");
        getContentPane().add(txtPrixUnitaire2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 90, -1));

        txtPrixUnitaire3.setEditable(false);
        txtPrixUnitaire3.setText("0");
        getContentPane().add(txtPrixUnitaire3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 90, -1));

        txtPrixUnitaire4.setEditable(false);
        txtPrixUnitaire4.setText("0");
        getContentPane().add(txtPrixUnitaire4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 90, -1));

        txtPrixUnitaire5.setEditable(false);
        txtPrixUnitaire5.setText("0");
        getContentPane().add(txtPrixUnitaire5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 90, -1));

        txtPrixUnitaire6.setEditable(false);
        txtPrixUnitaire6.setText("0");
        getContentPane().add(txtPrixUnitaire6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 90, -1));

        txtPrixUnitaire7.setEditable(false);
        txtPrixUnitaire7.setText("0");
        getContentPane().add(txtPrixUnitaire7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 90, -1));

        txtPrixUnitaire8.setEditable(false);
        txtPrixUnitaire8.setText("0");
        getContentPane().add(txtPrixUnitaire8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 90, -1));

        txtPrixUnitaire9.setEditable(false);
        txtPrixUnitaire9.setText("0");
        getContentPane().add(txtPrixUnitaire9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 90, -1));

        txtPrixUnitaire10.setEditable(false);
        txtPrixUnitaire10.setText("0");
        getContentPane().add(txtPrixUnitaire10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 90, -1));

        txtPrixUnitaire11.setEditable(false);
        txtPrixUnitaire11.setText("0");
        getContentPane().add(txtPrixUnitaire11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 90, -1));

        txtPrixUnitaire12.setEditable(false);
        txtPrixUnitaire12.setText("0");
        getContentPane().add(txtPrixUnitaire12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 90, -1));

        txtPrixUnitaire13.setEditable(false);
        txtPrixUnitaire13.setText("0");
        getContentPane().add(txtPrixUnitaire13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 90, -1));

        txtPrixUnitaire14.setEditable(false);
        txtPrixUnitaire14.setText("0");
        getContentPane().add(txtPrixUnitaire14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 90, -1));

        txtPrixUnitaire15.setEditable(false);
        txtPrixUnitaire15.setText("0");
        getContentPane().add(txtPrixUnitaire15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 90, -1));

        txtPrixUnitaire16.setEditable(false);
        txtPrixUnitaire16.setText("0");
        getContentPane().add(txtPrixUnitaire16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 90, -1));

        txtPrixUnitaire17.setEditable(false);
        txtPrixUnitaire17.setText("0");
        getContentPane().add(txtPrixUnitaire17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 90, -1));

        txtPrixUnitaire18.setEditable(false);
        txtPrixUnitaire18.setText("0");
        getContentPane().add(txtPrixUnitaire18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 90, -1));

        txtPrixUnitaire19.setEditable(false);
        txtPrixUnitaire19.setText("0");
        getContentPane().add(txtPrixUnitaire19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 90, -1));

        txtQte0.setEditable(false);
        txtQte0.setText("0");
        getContentPane().add(txtQte0, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 60, -1));

        txtQte1.setEditable(false);
        txtQte1.setText("0");
        getContentPane().add(txtQte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 60, -1));

        txtQte2.setEditable(false);
        txtQte2.setText("0");
        getContentPane().add(txtQte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 60, -1));

        txtQte3.setEditable(false);
        txtQte3.setText("0");
        getContentPane().add(txtQte3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 60, -1));

        txtQte4.setEditable(false);
        txtQte4.setText("0");
        getContentPane().add(txtQte4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 60, -1));

        txtQte5.setEditable(false);
        txtQte5.setText("0");
        getContentPane().add(txtQte5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 60, -1));

        txtQte6.setEditable(false);
        txtQte6.setText("0");
        getContentPane().add(txtQte6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 60, -1));

        txtQte7.setEditable(false);
        txtQte7.setText("0");
        getContentPane().add(txtQte7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 60, -1));

        txtQte8.setEditable(false);
        txtQte8.setText("0");
        getContentPane().add(txtQte8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 60, -1));

        txtQte9.setEditable(false);
        txtQte9.setText("0");
        getContentPane().add(txtQte9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 60, -1));

        txtQte10.setEditable(false);
        txtQte10.setText("0");
        getContentPane().add(txtQte10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 60, -1));

        txtQte11.setEditable(false);
        txtQte11.setText("0");
        getContentPane().add(txtQte11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 60, -1));

        txtQte12.setEditable(false);
        txtQte12.setText("0");
        getContentPane().add(txtQte12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 60, -1));

        txtQte13.setEditable(false);
        txtQte13.setText("0");
        getContentPane().add(txtQte13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 60, -1));

        txtQte14.setEditable(false);
        txtQte14.setText("0");
        getContentPane().add(txtQte14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 60, -1));

        txtQte15.setEditable(false);
        txtQte15.setText("0");
        getContentPane().add(txtQte15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 60, -1));

        txtQte16.setEditable(false);
        txtQte16.setText("0");
        getContentPane().add(txtQte16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 60, -1));

        txtQte17.setEditable(false);
        txtQte17.setText("0");
        getContentPane().add(txtQte17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 60, -1));

        txtQte18.setEditable(false);
        txtQte18.setText("0");
        getContentPane().add(txtQte18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 60, -1));

        txtQte19.setEditable(false);
        txtQte19.setText("0");
        getContentPane().add(txtQte19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 60, -1));

        txtDesignation0.setEditable(false);
        getContentPane().add(txtDesignation0, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 390, -1));

        txtDesignation1.setEditable(false);
        getContentPane().add(txtDesignation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 390, -1));

        txtDesignation2.setEditable(false);
        getContentPane().add(txtDesignation2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 390, -1));

        txtDesignation3.setEditable(false);
        getContentPane().add(txtDesignation3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 390, -1));

        txtDesignation4.setEditable(false);
        getContentPane().add(txtDesignation4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 390, -1));

        txtDesignation5.setEditable(false);
        getContentPane().add(txtDesignation5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 390, -1));

        txtDesignation6.setEditable(false);
        getContentPane().add(txtDesignation6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 390, -1));

        txtDesignation7.setEditable(false);
        getContentPane().add(txtDesignation7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 390, -1));

        txtDesignation8.setEditable(false);
        getContentPane().add(txtDesignation8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 390, -1));

        txtDesignation9.setEditable(false);
        getContentPane().add(txtDesignation9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 390, -1));

        txtDesignation10.setEditable(false);
        getContentPane().add(txtDesignation10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 390, -1));

        txtDesignation11.setEditable(false);
        getContentPane().add(txtDesignation11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 390, -1));

        txtDesignation12.setEditable(false);
        getContentPane().add(txtDesignation12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 390, -1));

        txtDesignation13.setEditable(false);
        getContentPane().add(txtDesignation13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 390, -1));

        txtDesignation14.setEditable(false);
        getContentPane().add(txtDesignation14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 390, -1));

        txtDesignation15.setEditable(false);
        getContentPane().add(txtDesignation15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 390, -1));

        txtDesignation16.setEditable(false);
        getContentPane().add(txtDesignation16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 390, -1));

        txtDesignation17.setEditable(false);
        getContentPane().add(txtDesignation17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 390, -1));

        txtDesignation18.setEditable(false);
        getContentPane().add(txtDesignation18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 390, -1));

        txtDesignation19.setEditable(false);
        getContentPane().add(txtDesignation19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 390, -1));

        txtNumero0.setEditable(false);
        getContentPane().add(txtNumero0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, -1));

        txtNumero1.setEditable(false);
        getContentPane().add(txtNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, -1));

        txtNumero2.setEditable(false);
        getContentPane().add(txtNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, -1));

        txtNumero3.setEditable(false);
        getContentPane().add(txtNumero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, -1));

        txtNumero4.setEditable(false);
        getContentPane().add(txtNumero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 90, -1));

        txtNumero5.setEditable(false);
        getContentPane().add(txtNumero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, -1));

        txtNumero6.setEditable(false);
        getContentPane().add(txtNumero6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, -1));

        txtNumero7.setEditable(false);
        getContentPane().add(txtNumero7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, -1));

        txtNumero8.setEditable(false);
        getContentPane().add(txtNumero8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 90, -1));

        txtNumero9.setEditable(false);
        getContentPane().add(txtNumero9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, -1));

        txtNumero10.setEditable(false);
        getContentPane().add(txtNumero10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 90, -1));

        txtNumero11.setEditable(false);
        getContentPane().add(txtNumero11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 90, -1));

        txtNumero12.setEditable(false);
        getContentPane().add(txtNumero12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 90, -1));

        txtNumero13.setEditable(false);
        getContentPane().add(txtNumero13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 90, -1));

        txtNumero14.setEditable(false);
        getContentPane().add(txtNumero14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 90, -1));

        txtNumero15.setEditable(false);
        getContentPane().add(txtNumero15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 90, -1));

        txtNumero16.setEditable(false);
        getContentPane().add(txtNumero16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 90, -1));

        txtNumero17.setEditable(false);
        getContentPane().add(txtNumero17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 90, -1));

        txtNumero18.setEditable(false);
        getContentPane().add(txtNumero18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 90, -1));

        txtNumero19.setEditable(false);
        getContentPane().add(txtNumero19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 90, -1));

        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setText("Num\u00e9ro");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, -1));

        lblDesignation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesignation.setText("D\u00e9signation");
        getContentPane().add(lblDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 390, -1));

        lblQuantite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantite.setText("Quantit\u00e9");
        getContentPane().add(lblQuantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 60, -1));

        lblPrixUnitaire.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrixUnitaire.setText("Prix unitaire");
        getContentPane().add(lblPrixUnitaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 90, -1));

        lblPrixTTC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrixTTC.setText("Prix TTC");
        getContentPane().add(lblPrixTTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 90, -1));

        lblNom.setText("Nom :");
        getContentPane().add(lblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, -1));

        txtNom.setEditable(false);
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, -1));

        lblPrenom.setText("Prenom :");
        getContentPane().add(lblPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 80, -1));

        txtPrenom.setEditable(false);
        getContentPane().add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 230, -1));

        lblTelephone.setText("T\u00e9l\u00e9phone :");
        getContentPane().add(lblTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        lblFax.setText("Fax :");
        getContentPane().add(lblFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, -1));

        txtTelephone.setEditable(false);
        getContentPane().add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 180, -1));

        txtFax.setEditable(false);
        getContentPane().add(txtFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 180, -1));

        lblAdresse.setText("Adresse :");
        getContentPane().add(lblAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txtAdresse.setEditable(false);
        getContentPane().add(txtAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 470, -1));

        lblCodePostal.setText("Code postal :");
        getContentPane().add(lblCodePostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtCodePostal.setEditable(false);
        getContentPane().add(txtCodePostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, -1));

        lblVille.setText("Ville :");
        getContentPane().add(lblVille, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        txtVille.setEditable(false);
        getContentPane().add(txtVille, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 190, -1));

        lblPays.setText("Pays :");
        getContentPane().add(lblPays, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        txtPays.setEditable(false);
        getContentPane().add(txtPays, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 190, -1));

        btnCalculer.setText("Calculer");
        getContentPane().add(btnCalculer, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 90, -1));

        getContentPane().add(cmboRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 120, -1));

        getContentPane().add(txtRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 130, -1));

        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 120, -1));

        rbtnCee.setText("Facture Cee");
        btngCeeOuExport.add(rbtnCee);
        getContentPane().add(rbtnCee, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 120, -1));

        rbtnExport.setText("Facture Export");
        btngCeeOuExport.add(rbtnExport);
        getContentPane().add(rbtnExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 120, -1));

        getContentPane().add(lblPrixHTOuPoidsBrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 100, -1));

        getContentPane().add(lblRemiseOuTVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 60, -1));

        getContentPane().add(lblTVAOuPoidsNet, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 100, -1));

        txtPrixTTC.setEditable(false);
        getContentPane().add(txtPrixTTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 90, -1));

        txtPrixHTOuPoidsBrut.setEditable(false);
        getContentPane().add(txtPrixHTOuPoidsBrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 90, -1));

        txtTVAOuPoidsNet.setEditable(false);
        getContentPane().add(txtTVAOuPoidsNet, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 90, -1));

        txtPrixTTCApresOuPrixHT.setEditable(false);
        getContentPane().add(txtPrixTTCApresOuPrixHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 90, -1));

        getContentPane().add(lblTTCRemiseOuHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 110, -1));

        txtRemiseOuTVA.setEditable(false);
        getContentPane().add(txtRemiseOuTVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 90, -1));

        getContentPane().add(lblTTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, -1, -1));

        txtNumeroFacture.setEditable(false);
        getContentPane().add(txtNumeroFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 90, -1));

        lblNumeroFacture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroFacture.setText("N\u00b0 Facture");
        getContentPane().add(lblNumeroFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 90, -1));

        btnPrecedent.setText("Precedent");
        btnPrecedent.setEnabled(false);
        btnPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedentActionPerformed(evt);
            }
        });

        getContentPane().add(btnPrecedent, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 120, -1));

        btnSuivant.setText("Suivant");
        btnSuivant.setEnabled(false);
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });

        getContentPane().add(btnSuivant, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 120, -1));

        menuFichier.setText("Fichier");
        itemFermer.setText("Fermer");
        itemFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFermerActionPerformed(evt);
            }
        });

        menuFichier.add(itemFermer);

        jMenuBar1.add(menuFichier);

        menuEdition.setText("Edition");
        itemModifier.setText("Modifier");
        menuEdition.add(itemModifier);

        itemSupprimer.setText("Supprimer");
        itemSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSupprimerActionPerformed(evt);
            }
        });

        menuEdition.add(itemSupprimer);

        jMenuBar1.add(menuEdition);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 900, 600);
    }//GEN-END:initComponents

    private void itemSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSupprimerActionPerformed
        //String numeroFacture = txtNumeroFacture.getText();
        boolean retour = Acceuil.baseDeDonneeFacture.Supprimer(txtNumeroFacture.getText());//numeroFacture);
        if(retour == true){
            JOptionPane.showMessageDialog (this, "La facture a été supprimé","OK",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_itemSupprimerActionPerformed

    private void btnPrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedentActionPerformed
        i = i - 1;
        if(i > -1){
            Facture nouveau;
            ListIterator index = retour.listIterator(i);
        
            nouveau = (Facture)index.next();
            txtNom.setText(nouveau.nom);
            txtPrenom.setText(nouveau.prenom);
            txtAdresse.setText(nouveau.adresse);
            txtCodePostal.setText(nouveau.codePostal);
            txtVille.setText(nouveau.ville);
            txtPays.setText(nouveau.pays);
            txtTelephone.setText(nouveau.telephone);
            txtFax.setText(nouveau.fax);
            txtNumeroFacture.setText(nouveau.numeroFacture);
            
            txtNumero0.setText(nouveau.numero[0]);
            txtNumero1.setText(nouveau.numero[1]);
            txtNumero2.setText(nouveau.numero[2]);
            txtNumero3.setText(nouveau.numero[3]);
            txtNumero4.setText(nouveau.numero[4]);
            txtNumero5.setText(nouveau.numero[5]);
            txtNumero6.setText(nouveau.numero[6]);
            txtNumero7.setText(nouveau.numero[7]);
            txtNumero8.setText(nouveau.numero[8]);
            txtNumero9.setText(nouveau.numero[9]);
            txtNumero10.setText(nouveau.numero[10]);
            txtNumero11.setText(nouveau.numero[11]);
            txtNumero12.setText(nouveau.numero[12]);
            txtNumero13.setText(nouveau.numero[13]);
            txtNumero14.setText(nouveau.numero[14]);
            txtNumero15.setText(nouveau.numero[15]);
            txtNumero16.setText(nouveau.numero[16]);
            txtNumero17.setText(nouveau.numero[17]);
            txtNumero18.setText(nouveau.numero[18]);
            txtNumero19.setText(nouveau.numero[19]);
        
            txtDesignation0.setText(nouveau.designation[0]);
            txtDesignation1.setText(nouveau.designation[1]);
            txtDesignation2.setText(nouveau.designation[2]);
            txtDesignation3.setText(nouveau.designation[3]);
            txtDesignation4.setText(nouveau.designation[4]);
            txtDesignation5.setText(nouveau.designation[5]);
            txtDesignation6.setText(nouveau.designation[6]);
            txtDesignation7.setText(nouveau.designation[7]);
            txtDesignation8.setText(nouveau.designation[8]);
            txtDesignation9.setText(nouveau.designation[9]);
            txtDesignation10.setText(nouveau.designation[10]);
            txtDesignation11.setText(nouveau.designation[11]);
            txtDesignation12.setText(nouveau.designation[12]);
            txtDesignation13.setText(nouveau.designation[13]);
            txtDesignation14.setText(nouveau.designation[14]);
            txtDesignation15.setText(nouveau.designation[15]);
            txtDesignation16.setText(nouveau.designation[16]);
            txtDesignation17.setText(nouveau.designation[17]);
            txtDesignation18.setText(nouveau.designation[18]);
            txtDesignation19.setText(nouveau.designation[19]);
        
            txtQte0.setText(String.valueOf(nouveau.qte[0]));
            txtQte1.setText(String.valueOf(nouveau.qte[1]));
            txtQte2.setText(String.valueOf(nouveau.qte[2]));
            txtQte3.setText(String.valueOf(nouveau.qte[3]));
            txtQte4.setText(String.valueOf(nouveau.qte[4]));
            txtQte5.setText(String.valueOf(nouveau.qte[5]));
            txtQte6.setText(String.valueOf(nouveau.qte[6]));
            txtQte7.setText(String.valueOf(nouveau.qte[7]));
            txtQte8.setText(String.valueOf(nouveau.qte[8]));
            txtQte9.setText(String.valueOf(nouveau.qte[9]));
            txtQte10.setText(String.valueOf(nouveau.qte[10]));
            txtQte11.setText(String.valueOf(nouveau.qte[11]));
            txtQte12.setText(String.valueOf(nouveau.qte[12]));
            txtQte13.setText(String.valueOf(nouveau.qte[13]));
            txtQte14.setText(String.valueOf(nouveau.qte[14]));
            txtQte15.setText(String.valueOf(nouveau.qte[15]));
            txtQte16.setText(String.valueOf(nouveau.qte[16]));
            txtQte17.setText(String.valueOf(nouveau.qte[17]));
            txtQte18.setText(String.valueOf(nouveau.qte[18]));
            txtQte19.setText(String.valueOf(nouveau.qte[19]));
        
            txtPrixUnitaire0.setText(String.valueOf(nouveau.prixUnitaire[0]));
            txtPrixUnitaire1.setText(String.valueOf(nouveau.prixUnitaire[1]));
            txtPrixUnitaire2.setText(String.valueOf(nouveau.prixUnitaire[2]));
            txtPrixUnitaire3.setText(String.valueOf(nouveau.prixUnitaire[3]));
            txtPrixUnitaire4.setText(String.valueOf(nouveau.prixUnitaire[4]));
            txtPrixUnitaire5.setText(String.valueOf(nouveau.prixUnitaire[5]));
            txtPrixUnitaire6.setText(String.valueOf(nouveau.prixUnitaire[6]));
            txtPrixUnitaire7.setText(String.valueOf(nouveau.prixUnitaire[7]));
            txtPrixUnitaire8.setText(String.valueOf(nouveau.prixUnitaire[8]));
            txtPrixUnitaire9.setText(String.valueOf(nouveau.prixUnitaire[9]));
            txtPrixUnitaire10.setText(String.valueOf(nouveau.prixUnitaire[10]));
            txtPrixUnitaire11.setText(String.valueOf(nouveau.prixUnitaire[11]));
            txtPrixUnitaire12.setText(String.valueOf(nouveau.prixUnitaire[12]));
            txtPrixUnitaire13.setText(String.valueOf(nouveau.prixUnitaire[13]));
            txtPrixUnitaire14.setText(String.valueOf(nouveau.prixUnitaire[14]));
            txtPrixUnitaire15.setText(String.valueOf(nouveau.prixUnitaire[15]));
            txtPrixUnitaire16.setText(String.valueOf(nouveau.prixUnitaire[16]));
            txtPrixUnitaire17.setText(String.valueOf(nouveau.prixUnitaire[17]));
            txtPrixUnitaire18.setText(String.valueOf(nouveau.prixUnitaire[18]));
            txtPrixUnitaire19.setText(String.valueOf(nouveau.prixUnitaire[19]));
        
            txtPrixTTC0.setText(String.valueOf(nouveau.prixTTC[0]));
            txtPrixTTC1.setText(String.valueOf(nouveau.prixTTC[1]));
            txtPrixTTC2.setText(String.valueOf(nouveau.prixTTC[2]));
            txtPrixTTC3.setText(String.valueOf(nouveau.prixTTC[3]));
            txtPrixTTC4.setText(String.valueOf(nouveau.prixTTC[4]));
            txtPrixTTC5.setText(String.valueOf(nouveau.prixTTC[5]));
            txtPrixTTC6.setText(String.valueOf(nouveau.prixTTC[6]));
            txtPrixTTC7.setText(String.valueOf(nouveau.prixTTC[7]));
            txtPrixTTC8.setText(String.valueOf(nouveau.prixTTC[8]));
            txtPrixTTC9.setText(String.valueOf(nouveau.prixTTC[9]));
            txtPrixTTC10.setText(String.valueOf(nouveau.prixTTC[10]));
            txtPrixTTC11.setText(String.valueOf(nouveau.prixTTC[11]));
            txtPrixTTC12.setText(String.valueOf(nouveau.prixTTC[12]));
            txtPrixTTC13.setText(String.valueOf(nouveau.prixTTC[13]));
            txtPrixTTC14.setText(String.valueOf(nouveau.prixTTC[14]));
            txtPrixTTC15.setText(String.valueOf(nouveau.prixTTC[15]));
            txtPrixTTC16.setText(String.valueOf(nouveau.prixTTC[16]));
            txtPrixTTC17.setText(String.valueOf(nouveau.prixTTC[17]));
            txtPrixTTC18.setText(String.valueOf(nouveau.prixTTC[18]));
            txtPrixTTC19.setText(String.valueOf(nouveau.prixTTC[19]));
            
            if(nouveau.getClass().getName().equals("Facture_Export")){
                Facture_Export retourExport = (Facture_Export)nouveau;
            
                NumberFormat nf = NumberFormat.getInstance();
                nf.setMaximumFractionDigits(2);
                
                lblTTC.setText("Prix TTC");
                txtPrixTTC.setText(nf.format(retourExport.getTotal_TTC()));
                
                lblRemiseOuTVA.setText("Remise");
                txtRemiseOuTVA.setText(nf.format(retourExport.getRemise()));
                
                lblTTCRemiseOuHT.setText("Prix avec remise");
                txtPrixTTCApresOuPrixHT.setText(nf.format(retourExport.getTotal_TTC_Apres()));
                
                lblTVAOuPoidsNet.setText("TVA");
                txtTVAOuPoidsNet.setText(nf.format(retourExport.getValeur_TVA()));
                
                lblPrixHTOuPoidsBrut.setText("Prix HT");
                txtPrixHTOuPoidsBrut.setText(nf.format(retourExport.getTotal_HT()));
            }
            
            if(nouveau.getClass().getName().equals("Facture_CEE")){
                Facture_CEE retourCee = (Facture_CEE)nouveau;
            
                NumberFormat nf = NumberFormat.getInstance();
                nf.setMaximumFractionDigits(2);
                
                lblTTC.setText("Prix TTC");
                txtPrixTTC.setText(nf.format(retourCee.getTotal_TTC()));
                
                lblRemiseOuTVA.setText("TVA");
                txtRemiseOuTVA.setText(nf.format(retourCee.getValeur_TVA()));
                
                lblTTCRemiseOuHT.setText("Prix HT");
                txtPrixTTCApresOuPrixHT.setText(nf.format(retourCee.getTotal_HT()));
                
                lblTVAOuPoidsNet.setText("Poids net");
                txtTVAOuPoidsNet.setText(nf.format(retourCee.getPoidsNet()));
                
                lblPrixHTOuPoidsBrut.setText("Poids brut");
                txtPrixHTOuPoidsBrut.setText(nf.format(retourCee.getPoidsBrut()));
            }
        }
        else
        {
            JOptionPane.showMessageDialog (this, "Fin de liste","Liste",JOptionPane.INFORMATION_MESSAGE);
            i = 0;
        }
    }//GEN-LAST:event_btnPrecedentActionPerformed

    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        i = i + 1;
        btnPrecedent.setEnabled(true);
        Facture nouveau;
        ListIterator index = retour.listIterator(i);
        if(index.hasNext()){
            nouveau = (Facture)index.next();
            txtNom.setText(nouveau.nom);
            txtPrenom.setText(nouveau.prenom);
            txtAdresse.setText(nouveau.adresse);
            txtCodePostal.setText(nouveau.codePostal);
            txtVille.setText(nouveau.ville);
            txtPays.setText(nouveau.pays);
            txtTelephone.setText(nouveau.telephone);
            txtFax.setText(nouveau.fax);
            txtNumeroFacture.setText(nouveau.numeroFacture);
            
            txtNumero0.setText(nouveau.numero[0]);
            txtNumero1.setText(nouveau.numero[1]);
            txtNumero2.setText(nouveau.numero[2]);
            txtNumero3.setText(nouveau.numero[3]);
            txtNumero4.setText(nouveau.numero[4]);
            txtNumero5.setText(nouveau.numero[5]);
            txtNumero6.setText(nouveau.numero[6]);
            txtNumero7.setText(nouveau.numero[7]);
            txtNumero8.setText(nouveau.numero[8]);
            txtNumero9.setText(nouveau.numero[9]);
            txtNumero10.setText(nouveau.numero[10]);
            txtNumero11.setText(nouveau.numero[11]);
            txtNumero12.setText(nouveau.numero[12]);
            txtNumero13.setText(nouveau.numero[13]);
            txtNumero14.setText(nouveau.numero[14]);
            txtNumero15.setText(nouveau.numero[15]);
            txtNumero16.setText(nouveau.numero[16]);
            txtNumero17.setText(nouveau.numero[17]);
            txtNumero18.setText(nouveau.numero[18]);
            txtNumero19.setText(nouveau.numero[19]);
        
            txtDesignation0.setText(nouveau.designation[0]);
            txtDesignation1.setText(nouveau.designation[1]);
            txtDesignation2.setText(nouveau.designation[2]);
            txtDesignation3.setText(nouveau.designation[3]);
            txtDesignation4.setText(nouveau.designation[4]);
            txtDesignation5.setText(nouveau.designation[5]);
            txtDesignation6.setText(nouveau.designation[6]);
            txtDesignation7.setText(nouveau.designation[7]);
            txtDesignation8.setText(nouveau.designation[8]);
            txtDesignation9.setText(nouveau.designation[9]);
            txtDesignation10.setText(nouveau.designation[10]);
            txtDesignation11.setText(nouveau.designation[11]);
            txtDesignation12.setText(nouveau.designation[12]);
            txtDesignation13.setText(nouveau.designation[13]);
            txtDesignation14.setText(nouveau.designation[14]);
            txtDesignation15.setText(nouveau.designation[15]);
            txtDesignation16.setText(nouveau.designation[16]);
            txtDesignation17.setText(nouveau.designation[17]);
            txtDesignation18.setText(nouveau.designation[18]);
            txtDesignation19.setText(nouveau.designation[19]);
        
            txtQte0.setText(String.valueOf(nouveau.qte[0]));
            txtQte1.setText(String.valueOf(nouveau.qte[1]));
            txtQte2.setText(String.valueOf(nouveau.qte[2]));
            txtQte3.setText(String.valueOf(nouveau.qte[3]));
            txtQte4.setText(String.valueOf(nouveau.qte[4]));
            txtQte5.setText(String.valueOf(nouveau.qte[5]));
            txtQte6.setText(String.valueOf(nouveau.qte[6]));
            txtQte7.setText(String.valueOf(nouveau.qte[7]));
            txtQte8.setText(String.valueOf(nouveau.qte[8]));
            txtQte9.setText(String.valueOf(nouveau.qte[9]));
            txtQte10.setText(String.valueOf(nouveau.qte[10]));
            txtQte11.setText(String.valueOf(nouveau.qte[11]));
            txtQte12.setText(String.valueOf(nouveau.qte[12]));
            txtQte13.setText(String.valueOf(nouveau.qte[13]));
            txtQte14.setText(String.valueOf(nouveau.qte[14]));
            txtQte15.setText(String.valueOf(nouveau.qte[15]));
            txtQte16.setText(String.valueOf(nouveau.qte[16]));
            txtQte17.setText(String.valueOf(nouveau.qte[17]));
            txtQte18.setText(String.valueOf(nouveau.qte[18]));
            txtQte19.setText(String.valueOf(nouveau.qte[19]));
        
            txtPrixUnitaire0.setText(String.valueOf(nouveau.prixUnitaire[0]));
            txtPrixUnitaire1.setText(String.valueOf(nouveau.prixUnitaire[1]));
            txtPrixUnitaire2.setText(String.valueOf(nouveau.prixUnitaire[2]));
            txtPrixUnitaire3.setText(String.valueOf(nouveau.prixUnitaire[3]));
            txtPrixUnitaire4.setText(String.valueOf(nouveau.prixUnitaire[4]));
            txtPrixUnitaire5.setText(String.valueOf(nouveau.prixUnitaire[5]));
            txtPrixUnitaire6.setText(String.valueOf(nouveau.prixUnitaire[6]));
            txtPrixUnitaire7.setText(String.valueOf(nouveau.prixUnitaire[7]));
            txtPrixUnitaire8.setText(String.valueOf(nouveau.prixUnitaire[8]));
            txtPrixUnitaire9.setText(String.valueOf(nouveau.prixUnitaire[9]));
            txtPrixUnitaire10.setText(String.valueOf(nouveau.prixUnitaire[10]));
            txtPrixUnitaire11.setText(String.valueOf(nouveau.prixUnitaire[11]));
            txtPrixUnitaire12.setText(String.valueOf(nouveau.prixUnitaire[12]));
            txtPrixUnitaire13.setText(String.valueOf(nouveau.prixUnitaire[13]));
            txtPrixUnitaire14.setText(String.valueOf(nouveau.prixUnitaire[14]));
            txtPrixUnitaire15.setText(String.valueOf(nouveau.prixUnitaire[15]));
            txtPrixUnitaire16.setText(String.valueOf(nouveau.prixUnitaire[16]));
            txtPrixUnitaire17.setText(String.valueOf(nouveau.prixUnitaire[17]));
            txtPrixUnitaire18.setText(String.valueOf(nouveau.prixUnitaire[18]));
            txtPrixUnitaire19.setText(String.valueOf(nouveau.prixUnitaire[19]));
        
            txtPrixTTC0.setText(String.valueOf(nouveau.prixTTC[0]));
            txtPrixTTC1.setText(String.valueOf(nouveau.prixTTC[1]));
            txtPrixTTC2.setText(String.valueOf(nouveau.prixTTC[2]));
            txtPrixTTC3.setText(String.valueOf(nouveau.prixTTC[3]));
            txtPrixTTC4.setText(String.valueOf(nouveau.prixTTC[4]));
            txtPrixTTC5.setText(String.valueOf(nouveau.prixTTC[5]));
            txtPrixTTC6.setText(String.valueOf(nouveau.prixTTC[6]));
            txtPrixTTC7.setText(String.valueOf(nouveau.prixTTC[7]));
            txtPrixTTC8.setText(String.valueOf(nouveau.prixTTC[8]));
            txtPrixTTC9.setText(String.valueOf(nouveau.prixTTC[9]));
            txtPrixTTC10.setText(String.valueOf(nouveau.prixTTC[10]));
            txtPrixTTC11.setText(String.valueOf(nouveau.prixTTC[11]));
            txtPrixTTC12.setText(String.valueOf(nouveau.prixTTC[12]));
            txtPrixTTC13.setText(String.valueOf(nouveau.prixTTC[13]));
            txtPrixTTC14.setText(String.valueOf(nouveau.prixTTC[14]));
            txtPrixTTC15.setText(String.valueOf(nouveau.prixTTC[15]));
            txtPrixTTC16.setText(String.valueOf(nouveau.prixTTC[16]));
            txtPrixTTC17.setText(String.valueOf(nouveau.prixTTC[17]));
            txtPrixTTC18.setText(String.valueOf(nouveau.prixTTC[18]));
            txtPrixTTC19.setText(String.valueOf(nouveau.prixTTC[19]));
            
            if(nouveau.getClass().getName().equals("Facture_Export")){
                Facture_Export retourExport = (Facture_Export)nouveau;
            
                NumberFormat nf = NumberFormat.getInstance();
                nf.setMaximumFractionDigits(2);
                
                lblTTC.setText("Prix TTC");
                txtPrixTTC.setText(nf.format(retourExport.getTotal_TTC()));
                
                lblRemiseOuTVA.setText("Remise");
                txtRemiseOuTVA.setText(nf.format(retourExport.getRemise()));
                
                lblTTCRemiseOuHT.setText("Prix avec remise");
                txtPrixTTCApresOuPrixHT.setText(nf.format(retourExport.getTotal_TTC_Apres()));
                
                lblTVAOuPoidsNet.setText("TVA");
                txtTVAOuPoidsNet.setText(nf.format(retourExport.getValeur_TVA()));
                
                lblPrixHTOuPoidsBrut.setText("Prix HT");
                txtPrixHTOuPoidsBrut.setText(nf.format(retourExport.getTotal_HT()));
            }
            
            if(nouveau.getClass().getName().equals("Facture_CEE")){
                Facture_CEE retourCee = (Facture_CEE)nouveau;
            
                NumberFormat nf = NumberFormat.getInstance();
                nf.setMaximumFractionDigits(2);
                
                lblTTC.setText("Prix TTC");
                txtPrixTTC.setText(nf.format(retourCee.getTotal_TTC()));
                
                lblRemiseOuTVA.setText("TVA");
                txtRemiseOuTVA.setText(nf.format(retourCee.getValeur_TVA()));
                
                lblTTCRemiseOuHT.setText("Prix HT");
                txtPrixTTCApresOuPrixHT.setText(nf.format(retourCee.getTotal_HT()));
                
                lblTVAOuPoidsNet.setText("Poids net");
                txtTVAOuPoidsNet.setText(nf.format(retourCee.getPoidsNet()));
                
                lblPrixHTOuPoidsBrut.setText("Poids brut");
                txtPrixHTOuPoidsBrut.setText(nf.format(retourCee.getPoidsBrut()));
            }
        }
        else
        {
            JOptionPane.showMessageDialog (this, "Fin de liste","Liste",JOptionPane.INFORMATION_MESSAGE);
            i = i - 1;
        }
    }//GEN-LAST:event_btnSuivantActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String type;
        String recherche = txtRecherche.getText();
        String typeRecherche = (String)cmboRecherche.getSelectedItem();
        boolean choixCee = rbtnCee.isSelected();
        boolean choixExport = rbtnExport.isSelected();
        
        if(!choixCee & !choixExport){
            JOptionPane.showMessageDialog (this, "Vous devez choisir un type de facture","Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            if(choixCee){
                type = "Facture_CEE";
            }
            else
            {
                type = "Facture_Export";
            }
            
                retour = Acceuil.baseDeDonneeFacture.rechercher(recherche, typeRecherche, type);
                if(retour.size() != 0){
                    btnSuivant.setEnabled(true);
                }
                else
                {
                    JOptionPane.showMessageDialog (this, "La recherche n'a pas aboutie","Erreur",JOptionPane.INFORMATION_MESSAGE);
                }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itemFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFermerActionPerformed
        dispose();
    }//GEN-LAST:event_itemFermerActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculer;
    private javax.swing.JButton btnPrecedent;
    private javax.swing.JButton btnSuivant;
    private javax.swing.ButtonGroup btngCeeOuExport;
    private javax.swing.JComboBox cmboRecherche;
    private javax.swing.JMenuItem itemFermer;
    private javax.swing.JMenuItem itemModifier;
    private javax.swing.JMenuItem itemSupprimer;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAdresse;
    private javax.swing.JLabel lblCodePostal;
    private javax.swing.JLabel lblDesignation;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroFacture;
    private javax.swing.JLabel lblPays;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JLabel lblPrixHTOuPoidsBrut;
    private javax.swing.JLabel lblPrixTTC;
    private javax.swing.JLabel lblPrixUnitaire;
    private javax.swing.JLabel lblQuantite;
    private javax.swing.JLabel lblRemiseOuTVA;
    private javax.swing.JLabel lblTTC;
    private javax.swing.JLabel lblTTCRemiseOuHT;
    private javax.swing.JLabel lblTVAOuPoidsNet;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblVille;
    private javax.swing.JMenu menuEdition;
    private javax.swing.JMenu menuFichier;
    private javax.swing.JRadioButton rbtnCee;
    private javax.swing.JRadioButton rbtnExport;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtCodePostal;
    private javax.swing.JTextField txtDesignation0;
    private javax.swing.JTextField txtDesignation1;
    private javax.swing.JTextField txtDesignation10;
    private javax.swing.JTextField txtDesignation11;
    private javax.swing.JTextField txtDesignation12;
    private javax.swing.JTextField txtDesignation13;
    private javax.swing.JTextField txtDesignation14;
    private javax.swing.JTextField txtDesignation15;
    private javax.swing.JTextField txtDesignation16;
    private javax.swing.JTextField txtDesignation17;
    private javax.swing.JTextField txtDesignation18;
    private javax.swing.JTextField txtDesignation19;
    private javax.swing.JTextField txtDesignation2;
    private javax.swing.JTextField txtDesignation3;
    private javax.swing.JTextField txtDesignation4;
    private javax.swing.JTextField txtDesignation5;
    private javax.swing.JTextField txtDesignation6;
    private javax.swing.JTextField txtDesignation7;
    private javax.swing.JTextField txtDesignation8;
    private javax.swing.JTextField txtDesignation9;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumero0;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero10;
    private javax.swing.JTextField txtNumero11;
    private javax.swing.JTextField txtNumero12;
    private javax.swing.JTextField txtNumero13;
    private javax.swing.JTextField txtNumero14;
    private javax.swing.JTextField txtNumero15;
    private javax.swing.JTextField txtNumero16;
    private javax.swing.JTextField txtNumero17;
    private javax.swing.JTextField txtNumero18;
    private javax.swing.JTextField txtNumero19;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextField txtNumero3;
    private javax.swing.JTextField txtNumero4;
    private javax.swing.JTextField txtNumero5;
    private javax.swing.JTextField txtNumero6;
    private javax.swing.JTextField txtNumero7;
    private javax.swing.JTextField txtNumero8;
    private javax.swing.JTextField txtNumero9;
    private javax.swing.JTextField txtNumeroFacture;
    private javax.swing.JTextField txtPays;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtPrixHTOuPoidsBrut;
    private javax.swing.JTextField txtPrixTTC;
    private javax.swing.JTextField txtPrixTTC0;
    private javax.swing.JTextField txtPrixTTC1;
    private javax.swing.JTextField txtPrixTTC10;
    private javax.swing.JTextField txtPrixTTC11;
    private javax.swing.JTextField txtPrixTTC12;
    private javax.swing.JTextField txtPrixTTC13;
    private javax.swing.JTextField txtPrixTTC14;
    private javax.swing.JTextField txtPrixTTC15;
    private javax.swing.JTextField txtPrixTTC16;
    private javax.swing.JTextField txtPrixTTC17;
    private javax.swing.JTextField txtPrixTTC18;
    private javax.swing.JTextField txtPrixTTC19;
    private javax.swing.JTextField txtPrixTTC2;
    private javax.swing.JTextField txtPrixTTC3;
    private javax.swing.JTextField txtPrixTTC4;
    private javax.swing.JTextField txtPrixTTC5;
    private javax.swing.JTextField txtPrixTTC6;
    private javax.swing.JTextField txtPrixTTC7;
    private javax.swing.JTextField txtPrixTTC8;
    private javax.swing.JTextField txtPrixTTC9;
    private javax.swing.JTextField txtPrixTTCApresOuPrixHT;
    private javax.swing.JTextField txtPrixUnitaire0;
    private javax.swing.JTextField txtPrixUnitaire1;
    private javax.swing.JTextField txtPrixUnitaire10;
    private javax.swing.JTextField txtPrixUnitaire11;
    private javax.swing.JTextField txtPrixUnitaire12;
    private javax.swing.JTextField txtPrixUnitaire13;
    private javax.swing.JTextField txtPrixUnitaire14;
    private javax.swing.JTextField txtPrixUnitaire15;
    private javax.swing.JTextField txtPrixUnitaire16;
    private javax.swing.JTextField txtPrixUnitaire17;
    private javax.swing.JTextField txtPrixUnitaire18;
    private javax.swing.JTextField txtPrixUnitaire19;
    private javax.swing.JTextField txtPrixUnitaire2;
    private javax.swing.JTextField txtPrixUnitaire3;
    private javax.swing.JTextField txtPrixUnitaire4;
    private javax.swing.JTextField txtPrixUnitaire5;
    private javax.swing.JTextField txtPrixUnitaire6;
    private javax.swing.JTextField txtPrixUnitaire7;
    private javax.swing.JTextField txtPrixUnitaire8;
    private javax.swing.JTextField txtPrixUnitaire9;
    private javax.swing.JTextField txtQte0;
    private javax.swing.JTextField txtQte1;
    private javax.swing.JTextField txtQte10;
    private javax.swing.JTextField txtQte11;
    private javax.swing.JTextField txtQte12;
    private javax.swing.JTextField txtQte13;
    private javax.swing.JTextField txtQte14;
    private javax.swing.JTextField txtQte15;
    private javax.swing.JTextField txtQte16;
    private javax.swing.JTextField txtQte17;
    private javax.swing.JTextField txtQte18;
    private javax.swing.JTextField txtQte19;
    private javax.swing.JTextField txtQte2;
    private javax.swing.JTextField txtQte3;
    private javax.swing.JTextField txtQte4;
    private javax.swing.JTextField txtQte5;
    private javax.swing.JTextField txtQte6;
    private javax.swing.JTextField txtQte7;
    private javax.swing.JTextField txtQte8;
    private javax.swing.JTextField txtQte9;
    private javax.swing.JTextField txtRecherche;
    private javax.swing.JTextField txtRemiseOuTVA;
    private javax.swing.JTextField txtTVAOuPoidsNet;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtVille;
    // End of variables declaration//GEN-END:variables
    
}
